<script>
	import {mapActions, mapGetters, mapState} from 'vuex'
	export default {
		computed: {
			... mapState({
			}),
			... mapGetters( {//перечень функций из стандартных vuex
				compDialogByName: "compDialog/getByName",
				compDialogConfig: "compDialog/getConfig",
				compDialogParams: "compDialog/getParams",
				compDialogIsShow: "compDialog/getIsShow",
				compDialogShowen: "compDialog/getShowen",
				msgAllMsg: "msg/getAllMsg",
				msgMsg: "msg/getMsg",
				msgMsgIndex: "msg/getMsgIndex",
				paramConfigGroup: "paramConfig/getGroup",
				paramConfigTypes: "paramConfig/getTypes",
				paramByCode: "param/getByCode",
				paramValByCode: "param/getValByCode",
				paramValFieldByData: "param/getValFieldByData",
				paramGroup: "param/getGroup",
				paramInfo: "param/getParamsInfo",
				paramToObj: "param/getParamsToObj",
				paramInfoChecked: "param/getParamsInfoChecked",
				compButtonByName:"compButton/getByName",
				compButtonDisable:"compButton/getDisable",
				compButtonLockByName:"compButton/getLockByName",
				compButtonLoading:"compButton/getLoading",
				profileUserInfo: "profile/getUserInfo",
				profileIsRoot: "profile/getIsRoot",
				profileAvatar: "profile/getAvatar",
				profileUserId: "profile/getUserId",
				profileUserLogin: "profile/getUserLogin",
				profileUserName: "profile/getUserName",
				profileLanguage: "profile/getLanguage",
				profileToken: "profile/getToken",
				profileExpiresIn: "profile/getExpiresIn",
				profileRefreshToken: "profile/getRefreshToken",
				profileTokenType: "profile/getTokenType",
				profileTokenRemember: "profile/getTokenRemember",
				layoutByHead: "layout/getByHead",
				layoutDescByHead: "layout/getDescByHead",
				layoutDescByName: "layout/getDescByName",
				layoutSizePxByHead: "layout/getSizePxByHead",
				layoutSizePxByName: "layout/getSizePxByName",
				layoutLink: "layout/getLink",
				layoutLinkObj: "layout/getLinkObj",
				layoutLinkChilds: "layout/getLinkChilds",
				systemCurArmName : "system/getCurArmName",
				} ) ,	
		},
		methods: {
			... mapActions({
				compDialogInit: "compDialog/doInit",
				compDialogSetAllParams: "compDialog/doSetAllParams",
				compDialogSetParam: "compDialog/doSetParam",
				compDialogShowChange: "compDialog/doShowChange",
				compDialogClear: "compDialog/doClear",
				msgAdd: "msg/doAdd",
				msgDelete: "msg/doDelete",
				compButtonInit:"compButton/doInit",
				compButtonClear:"compButton/doClear",
				compButtonAdd:"compButton/doAdd",
				compButtonEdit:"compButton/doEdit",
				compButtonSetDisable:"compButton/doSetDisable",
				compButtonSetLoading:"compButton/doSetLoading",
				compButtonSetLock:"compButton/doSetLock",
				paramConfigInit: "paramConfig/doInit",
				paramInit: "param/doInit",
				paramSetData: "param/doSetData",
				paramSet: "param/doSet",
				paramSetValOutside: "param/doSetValOutside",
				paramSetSeveralValOutside: "param/doSetSeveralValOutside",
				paramSetAll: "param/doSetAll",
				paramSetSeveral: "param/doSetSeveral",
				paramClear: "param/doClear",
				profileLog: "profile/doLog",
				profileLogout: "profile/doLogout",
				profileSetToken: "profile/doSetToken",
				layoutInit: "layout/doInit",
				layoutSizeSet: "layout/doSizeSet",
				layoutSizePxRecalc: "layout/doSizePxRecalc",
				layoutSizePxChange: "layout/doSizePxChange",
				layoutLinkSet: "layout/doLinkSet",
				layoutLinkDel: "layout/doLinkDel",
				systemCurArmNameChange: "system/doCurArmNameChange",
			}) ,	
		},
	}
</script>