<script>
	import {mapActions, mapGetters, mapState} from 'vuex'
	export default {
		computed: {
			... mapState({
			}),
			... mapGetters( {//перечень функций из стандартных vuex
				dialogById: "dialog/getById",
				dialogByName: "dialog/getByName",
				dialogConfig: "dialog/getConfig",
				dialogDilog: "dialog/getDilog",
				dialogParams: "dialog/getParams",
				dialogIsShow: "dialog/getIsShow",
				msgAllMsg: "msg/getAllMsg",
				msgMsg: "msg/getMsg",
				msgMsgIndex: "msg/getMsgIndex",
				paramConfigGroup: "paramConfig/getGroup",
				paramByCode: "param/getByCode",
				paramValByCode: "param/getValByCode",
				paramValFieldByData: "param/getValFieldByData",
				paramGroup: "param/getGroup",
				paramInfo: "param/getParamsInfo",
				paramToObj: "param/getParamsToObj",
				paramInfoChecked: "param/getParamsInfoChecked",
				profileUserInfo: "profile/getUserInfo",
				profileIsRoot: "profile/getIsRoot",
				profileAvatar: "profile/getAvatar",
				profileUserId: "profile/getUserId",
				profileUserLogin: "profile/getUserLogin",
				profileUserName: "profile/getUserName",
				profileLanguage: "profile/getLanguage",
				profileToken: "profile/getToken",
				profileExpiresIn: "profile/getExpiresIn",
				profileRefreshToken: "profile/getRefreshToken",
				profileTokenType: "profile/getTokenType",
				profileTokenRemember: "profile/getTokenRemember",
				layoutByHead: "layout/getByHead",
				layoutDescByHead: "layout/getDescByHead",
				layoutDescByName: "layout/getDescByName",
				layoutSizePxByHead: "layout/getSizePxByHead",
				layoutSizePxByName: "layout/getSizePxByName",
				layoutLink: "layout/getLink",
				layoutLinkObj: "layout/getLinkObj",
				layoutLinkChilds: "layout/getLinkChilds",
				} ) ,	
		},
		methods: {
			... mapActions({
				dialogInit: "dialog/doInit",
				dialogSetAllParams: "dialog/doSetAllParams",
				dialogSetAllParamsAndShow: "dialog/doSetAllParamsAndShow",
				dialogSetParamByName: "dialog/doSetParamByName",
				dialogSetParamByNameAndShow: "dialog/doSetParamByNameAndShow",
				dialogShowChange: "dialog/doShowChange",
				msgAdd: "msg/doAdd",
				msgDelete: "msg/doDelete",
				paramConfigInit: "paramConfig/doInit",
				paramInit: "param/doInit",
				paramSetData: "param/doSetData",
				paramSet: "param/doSet",
				paramSetValOutside: "param/doSetValOutside",
				paramSetSeveralValOutside: "param/doSetSeveralValOutside",
				paramSetAll: "param/doSetAll",
				paramSetSeveral: "param/doSetSeveral",
				profileLog: "profile/doLog",
				profileLogout: "profile/doLogout",
				profileSetToken: "profile/doSetToken",
				layoutInit: "layout/doInit",
				layoutSizeSet: "layout/doSizeSet",
				layoutSizePxRecalc: "layout/doSizePxRecalc",
				layoutSizePxChange: "layout/doSizePxChange",
				layoutLinkSet: "layout/doLinkSet",
				layoutLinkDel: "layout/doLinkDel",
			}) ,	
		},
	}
</script>