<script>
	import {mapActions, mapGetters, mapState} from 'vuex'
	export default {
		computed: {
			... mapState({
				stateParams:'param/params'
			}),
			... mapGetters( {//перечень функций из стандартных vuex
				dialogById: "dialog/getById",
				dialogByName: "dialog/getByName",
				dialogConfig: "dialog/getConfig",
				dialogDilog: "dialog/getDilog",
				dialogParams: "dialog/getParams",
				dialogIsShow: "dialog/getIsShow",
				msgAllMsg: "msg/getAllMsg",
				msgMsg: "msg/getMsg",
				msgMsgIndex: "msg/getMsgIndex",
				paramByCode: "param/getByCode",
				paramValByCode: "param/getValByCode",
				paramValFieldByData: "param/getValFieldByData",
				paramGroup: "param/getGroup",
				paramTodo: "param/getTodo",
				paramTodoChecked: "param/getTodoChecked",
				profileIsRoot: "profile/getIsRoot",
				profileAvatar: "profile/getAvatar",
				profileUserId: "profile/getUserId",
				profileUserName: "profile/getUserName",
				profileLanguage: "profile/getLanguage",
				layoutByName: "layout/getByName",
				layoutDescByHead: "layout/getDescByHead",
				layoutDescByName: "layout/getDescByName",
				layoutSizePxByHead: "layout/getSizePxByHead",
				layoutSizePxByName: "layout/getSizePxByNa me",
				} ) ,	
		},
		methods: {
			... mapActions({
				dialogInit: "dialog/doInit",
				dialogSetAllParams: "dialog/doSetAllParams",
				dialogSetAllParamsAndShow: "dialog/doSetAllParamsAndShow",
				dialogSetParamByName: "dialog/doSetParamByName",
				dialogSetParamByNameAndShow: "dialog/doSetParamByNameAndShow",
				dialogShowChange: "dialog/doShowChange",
				msgAdd: "msg/doAdd",
				msgDelete: "msg/doDelete",
				paramInit: "param/doInit",
				paramSetData: "param/doSetData",
				paramSet: "param/doSet",
				paramSetValOutside: "param/doSetValOutside",
				paramSetSeveralValOutside: "param/doSetSeveralValOutside",
				paramSetAll: "param/doSetAll",
				paramSetSeveral: "param/doSetSeveral",
				profileLog: "profile/doLog",
				profileLogout: "profile/doLogout",
				layoutInit: "layout/doInit",
				layoutSizeSet: "layout/doSizeSet",
				layoutSizePxRecalc: "layout/doSizePxRecalc",
				layoutSizePxChange: "layout/doSizePxChange",
			}) ,	
		},
	}
</script>